Project/config/routes.rb
SinaiMount::Application.routes.draw do

  devise_for :users

  scope '/administration', module: 'administration', as: 'administration' do
    resources :countries, except: [:show, :destroy]
    resources :states, except: [:show, :destroy]
    resources :cities, except: [:show, :destroy]
    resources :jobs, except: [:destroy]
    resources :churches, except: [:destroy]
    resources :shepherds, except: [:destroy]
    resources :congregateds, except: [:destroy]
    resources :posts, except: [:destroy]
    resources :members, except: [:destroy] do
      get :naturalness, on: :collection
    end
  end

  get :cities_of_state, to: 'application#cities_of_state'

  get :show_address, to: 'application#show_address'

  root to: 'home#index'

  get '*a', to: 'application#render_error'
end

Project/app/models/member.rb
class Member < ActiveRecord::Base
  attr_accessible :name, :father_name, :mother_name, :post_id, :naturalness_id, :job_id,
                  :convert_dt, :birth_dt, :gender, :educational_level, :marital_status, :address_attributes
  attr_list :id, :name
  attr_search :name

  attr_accessor :state_id, :country_id

  has_enumeration_for :gender, with: Gender
  has_enumeration_for :educational_level, with: LevelOfStudy
  has_enumeration_for :marital_status, with: MaritalStatus

  belongs_to :job
  belongs_to :post
  belongs_to :naturalness, class_name: 'City'

  has_one :address, as: :related, dependent: :destroy

  accepts_nested_attributes_for :address, update_only: true

  has_attached_file :photo,
                    url: "/anexos/:class/:attachment/:id/:style_:basename.:extension",
                    path: ":rails_root/public/anexos/:class/:attachment/:id/:style_:basename.:extension"


  validates :name, :father_name, :mother_name, :post_id, :naturalness_id, :job_id,
            :convert_dt, :birth_dt, :gender, :educational_level, :marital_status, presence: true

  validates :name, uniqueness: true

  orderize :name
  filterize

  def to_s
    name
  end
end

Project/app/controllers/administration/churches_controller.rb
class Administration::ChurchesController < CrudController
end

Project/app/controllers/administration/cities_controller.rb
class Administration::CitiesController < CrudController
  def update
    update! do
      edit_administration_city_path(country_id: params[:country_id], state_id: params[:state_id])
    end
  end

  def create
    create! do
      administration_cities_path(redirect_index)
    end
  end

  def activate
    activate!(redirect_index(false))
  end

  def inactivate
    inactivate!(redirect_index)
  end

  protected

  def redirect_index(active=nil)
    {country_id: params[:country_id],
     state_id: params[:state_id],
     active: active}
  end

  def end_of_association_chain
    apply_scopes City.by_state params[:state_id]
  end
end

Project/app/controllers/administration/congregateds_controller.rb
class Administration::CongregatedsController < CrudController
end

Project/app/controllers/administration/countries_controller.rb
class Administration::CountriesController < CrudController
end

Project/app/controllers/administration/jobs_controller.rb
class Administration::JobsController < CrudController
end

Project/app/controllers/administration/members_controller.rb
class Administration::MembersController < CrudController
end

Project/app/controllers/administration/posts_controller.rb
class Administration::PostsController < CrudController
end

Project/app/controllers/administration/shepherds_controller.rb
class Administration::ShepherdsController < CrudController
end

Project/app/controllers/administration/states_controller.rb
class Administration::StatesController < CrudController
  def update
    update! do
      edit_administration_state_path(country_id: params[:country_id])
    end
  end

  def create
    create! do
      administration_states_path(redirect_index)
    end
  end

  def activate
    activate!(redirect_index(false))
  end

  def inactivate
    inactivate!(redirect_index)
  end

  protected

  def end_of_association_chain
    apply_scopes State.by_country params[:country_id]
  end

  def redirect_index(active=nil)
    {country_id: params[:country_id],
     active: active}
  end
end

Project/app/views/administration/members/_form.html.erb
<%= info_box I18n.t 'general_data', 'span2' do %>
  <%= f.input :name,
              input_html: { class: 'field-user', style: span_30 } %>
  <%= f.input :father_name,
              input_html: { class: 'field-user', style: span_30 } %>
  <%= f.input :mother_name,
              input_html: { class: 'field-user', style: span_30 } %>
  <%= f.input :country_id,
              collection: Country.all,
              selected: f.object.new_record? ? nil : f.object.naturalness.state.country_id,
              input_html: { style: span_15,  } %>
  <%= f.input :state_id,
              collection:  f.object.new_record? ? [] : f.object.naturalness.state.country.states,
              selected: f.object.new_record? ? nil : f.object.naturalness.state_id,
              input_html: { style: span_15 } %>
  <%= f.input :naturalness,
              collection: f.object.new_record? ? [] : f.object.naturalness.state.cities,
              selected: f.object.new_record? ? nil : f.object.naturalness_id,
              input_html: { style: span_15 } %>
  <%= f.input :photo %>
  <%= f.input :job,
              input_html: { style: span_30 } %>
  <%= f.input :birth_dt,
              input_html: { class: 'date-picker', style: span_date } %>
  <%= f.input :gender,
              input_html: { style: span_10 } %>
  <%= f.input :educational_level,
              input_html: { style: span_15 } %>
  <%= f.input :marital_status,
              input_html: { style: span_15 } %>
<% end %>

<%= info_box I18n.t 'info_box.member_data', 'span2' do %>
  <%= f.input :post, input_html: { style: span_30 } %>
  <%= f.input :convert_dt, input_html: { class: 'date-picker', style: span_date } %>
<% end %>

<%= info_box I18n.t 'activerecord.models.address.one', 'span2' do %>
  <%= render 'shared/address', f: f %>
<% end %>

<script type="text/javascript">
  jQuery(function(){
    var url = '<%= naturalness_administration_members_path %>';

    $('#member_country_id').change(function(){
      buscar_dados($(this).val(), 'country_id');
    });

    $('#member_state_id').change(function(){
      buscar_dados($(this).val(), 'state_id');
    });

    function buscar_dados(value, type){
      $.get(url, {value: value, type: type}, 'script');
    }
  });
</script>

Project/app/views/administration/members/_list_body.html.erb
<% collection(params).each do |object| %>
  <tr id="<%= dom_id object %>">
    <% resource_class.list_attributes.each do |attribute| %>
      <td>
        <%= formatted_attribute(object, attribute) %>
      </td>
    <% end %>
    <td>
      <%= icons { render 'list_icons', object: object } %>
    </td>
  </tr>
<% end %>

Project/app/views/administration/members/_list_head.html.erb
<tr>
  <% attr_filtered = resource_class.list_attributes - ['id'] %>
  <th <%= icon_3 %>><%= localized_attribute(resource_class, 'id') %></th>

  <% attr_filtered.each do |attribute| %>
    <th><%= localized_attribute(resource_class, attribute) %></th>
  <% end %>
  <th <%= icon_3 %>></th>
</tr>

Project/app/views/administration/members/_show.html.erb
<%= info_box(I18n.t '.general_data') do %>
  <% [:name, :father_name, :mother_name, :naturalness,
      :birth_dt, :gender, :educational_level, :marital_status, :job_id].each do |attribute| %>
    <% if resource.respond_to? real_attribute(attribute) %>
      <%= show_attribute(attribute) %>
    <% end %>
  <% end %>
<% end %>

<%= info_box I18n.t 'info_box.member_data', 'span2' do %>
  <% [:post, :convert_dt].each do |attribute|  %>
    <% if resource.respond_to? real_attribute(attribute) %>
      <%= show_attribute(attribute) %>
    <% end %>
  <% end %>
<% end %>

<%= render 'shared/address_show' %>

Project/app/views/administration/members/naturalness.js.erb
if('<%= params[:type] %>' == 'country_id'){
  <% states = State.by_country(params[:value]).collect { |s| ["#{s.acronym} - #{s.name}", s.id] } %>
  $("#member_state_id").html('<%= escape_javascript(options_for_select(states)) %>;');
}
else
if('<%= params[:type] %>' == 'state_id'){
  <% cities = City.by_state(params[:value]).collect { |s| [s.name, s.id] } %>
  $("#member_naturalness_id").html('<%= escape_javascript(options_for_select(cities)) %>;');
}