Project/config/routes.rb
SinaiMount::Application.routes.draw do

  devise_for :users

  scope '/administration', module: 'administration', as: 'administration' do
    resources :countries, except: [:show, :destroy]
    resources :states, except: [:show, :destroy]
    resources :cities, except: [:show, :destroy]
    resources :jobs, except: [:destroy]
    resources :churches, except: [:destroy]
    resources :shepherds, except: [:destroy]
    resources :congregateds, except: [:destroy]
    resources :posts, except: [:destroy]
    resources :members, except: [:destroy] do
      get :naturalness, on: :collection
    end
  end

  get :cities_of_state, to: 'application#cities_of_state'

  get :show_address, to: 'application#show_address'

  root to: 'home#index'

  get '*a', to: 'application#render_error'
end

Project/app/views/shared/_address.html.erb
<div class='address'>
  <% unless f.object.address.blank? %>
    <% state_id = f.object.address.city.state_id %>
    <% cities = f.object.address.city.state.cities %>
<% else %>
    <% state_id = cities = [] %>
  <% end %>
<% states = State.all.collect { |s| ["#{s.acronym} - #{s.name}", s.id] } %>

  <%= f.simple_fields_for :address_attributes, f.object.address || f.object.build_address do |a| %>
    <%= a.input :zipcode, input_html: {class: 'mask-zipcode', style: 'width: 5.6% !important'}, style: 'float:left; margin-right:2%',
                hint: raw("<div style='margin-top:0.5%;'>#{ link_to "Consultar CEP", "http://www.correios.com.br", target: '_blank' }</div>") %>
    <%= a.input :state, collection: states, selected: state_id,
                prompt: 'Selecione', input_html: { style: span_20 } %>
    <%= a.input :city, collection: cities,
                prompt: 'Digite um CEP ou Selecione um Estado',
                input_html: { style: span_20 } %>
    <%= a.input :district, input_html: { style: span_15 } %>
    <%= a.input :street, input_html: { style: span_30 } %>
    <%= a.input :complement, input_html: { style: span_30 } %>
    <%= a.input :number, input_html: { style: span_5 } %>
    <%= a.input :reference_point, as: :text, input_html: { style: span_30 } %>
    <%= a.input :lat, input_html: { class: 'field-coordinate',
                                    data: { negative: true },
                                    value: resource.address.lat,
                                    style: span_10 } %>
    <%= a.input :long, input_html: { class: 'field-coordinate',
                                     data: { negative: true },
                                     value: resource.address.long,
                                     style: span_10 } %>
  <% end %>
</div>

<script type="text/javascript">
  if (environment != 'test') {
    jQuery(function(){
      $("input[id$='zipcode']").change( function () {
        var url = '<%= show_address_path %>';
        $.get(url, {zipcode: $(this).val(), klass: '<%= resource.class %>'}, 'script');
      });
    });
  }
  jQuery(function() {
    $("select[id$='state']").change(function () {
      var url = '<%= cities_of_state_path %>';
      $.get(url, {state_id: $(this).val(), klass: '<%= resource.class %>'}, 'script');
    });
  });
</script>

Project/app/views/shared/_address_show.html.erb
<%= info_box t 'address' do %>
  <%="<b>#{t 'activerecord.models.city.one'}:</b>  #{resource.address.city.name}".html_safe %>
  <br />
  <% [:street, :number, :district, :zipcode, :lat, :long, :reference_point].each do |a| %>
    <%= show_attribute(a, resource.address) %>
  <% end %>
<% end %>

Project/app/views/shared/_cities_of_state.js.erb
<% name_of_class = params[:klass].downcase %>
$("#<%= name_of_class %>_address_attributes_city_id").html('<%= escape_javascript(options_for_select(@cities)) %>;');

Project/app/views/shared/_simple_fields_for.html.erb
<%= f.simple_fields_for relation do |rel| %>
  <%= render partial, f: rel %>
<% end %>
<div class='form-actions links'>
  <%= link_to_add_association 'Adicionar', f,
                              relation, partial: partial %>
</div>

Project/app/views/shared/_tree_data.html.erb
<script type="text/javascript">
  var DataSourceTree = function(options) {
    this._data 	= options.data;
    this._delay = options.delay;
  }

  DataSourceTree.prototype.data = function(options, callback) {
    var self = this;
    var $data = null;

    if(!("name" in options) && !("type" in options)){
      $data = this._data;//the root tree
      callback({ data: $data });
      return;
    }
    else if("type" in options && options.type == "folder") {
      if("additionalParameters" in options && "children" in options.additionalParameters)
        $data = options.additionalParameters.children;
      else $data = {}//no data
    }

    if($data != null)//this setTimeout is only for mimicking some random delay
      setTimeout(function(){callback({ data: $data });} , parseInt(Math.random() * 500) + 200);

    //you can retrieve your data from a server using ajax call
  };

  var treeDataSource = new DataSourceTree({data: <%= objects.to_json.html_safe %>});

  $(function(){
    $('#tree1').ace_tree({
      dataSource: treeDataSource ,
      multiSelect: false,
      loadingHTML:'<div class="tree-loading"><i class="icon-refresh icon-spin blue"></i></div>',
      'open-icon' : 'icon-minus',
      'close-icon' : 'icon-plus',
      'selectable' : false,
      'selected-icon' : 'icon-ok',
      'unselected-icon' : ''
    });
  });
</script>